### ISSUE TITLE
Convergence issues in NAFTA example

### ISSUE THREAD

**Issue by zauster** [pachadotdev/tradepolicy#1]
Hey Pachá,

thanks a lot for your work to make international trade research easier to do with R!

I had a closer look at your implementation of the 'Advanced Guide', chapter 2, NAFTA example.

1) You arrive at different results compared to the ones shown in the book:

```
  exporter change_rgdp_full change_xi_full change_imr_full change_omr_full
  <chr>               <dbl>          <dbl>           <dbl>           <dbl>
1 CAN                 3.43            36.9          -1.45           -2.20 
2 MEX                 3.82            43.2          -2.38           -1.55 
3 USA                 0.331           15.0          -0.199          -0.153
```
The GDP numbers in the book are approximately half of what you calculate. The export number are very similar to the ones in the book. The OMR and IMR changes are also different from the book.

This is also something that I found in my implementation of the structural gravity estimations: https://gitlab.com/zauster/geppml

2) I know that it is programmed like that in the book, but I am still convinced that `abs` and `max` should to be interchanged here:

https://github.com/pachadotdev/tradepolicy/blob/0cc0da8c62fab796d4a5f4b4965879fa09ba2d72/02-general-equilibrium.Rmd#L794

It doesn't make sense to first take the `max` and then the `abs`. In this case we say the algorithm converges if the prices do not increase anymore (but they could still be decreasing)...
However, if you interchange the two, the while loop does not stop because `max_dif` is then never smaller than 0.001 (in this example at least). Any thoughts on this?

Best,
Oliver

**Comment by pachadotdev** [comment]
> Hey Pachá,
> 
> thanks a lot for your work to make international trade research easier to do with R!
> 
> I had a closer look at your implementation of the 'Advanced Guide', chapter 2, NAFTA example.
> 
>     1. You arrive at different results compared to the ones shown in the book:
> 
> 
> ```
>   exporter change_rgdp_full change_xi_full change_imr_full change_omr_full
>   <chr>               <dbl>          <dbl>           <dbl>           <dbl>
> 1 CAN                 3.43            36.9          -1.45           -2.20 
> 2 MEX                 3.82            43.2          -2.38           -1.55 
> 3 USA                 0.331           15.0          -0.199          -0.153
> ```
> 
> The GDP numbers in the book are approximately half of what you calculate. The export number are very similar to the ones in the book. The OMR and IMR changes are also different from the book.
> 
> This is also something that I found in my implementation of the structural gravity estimations: https://gitlab.com/zauster/geppml
> 
>     2. I know that it is programmed like that in the book, but I am still convinced that `abs` and `max` should to be interchanged here:
> 
> 
> https://github.com/pachadotdev/tradepolicy/blob/0cc0da8c62fab796d4a5f4b4965879fa09ba2d72/02-general-equilibrium.Rmd#L794
> 
> It doesn't make sense to first take the `max` and then the `abs`. In this case we say the algorithm converges if the prices do not increase anymore (but they could still be decreasing)... However, if you interchange the two, the while loop does not stop because `max_dif` is then never smaller than 0.001 (in this example at least). Any thoughts on this?
> 
> Best, Oliver

Hi @zauster 
So sorry, I just saw this. I'll look at the model again and I'll update the ebook.

**Comment by zauster** [comment]
No worries, it's not urgent

**Comment by pachadotdev** [comment]
> No worries, it's not urgent

Hi!
Prof Yotov told me that the idea is for the stopping criteria to be such that the model converges when prices stop changing. He also told me that he's working on changes to the book and that he'll have a look at the specific code.
