### ISSUE TITLE
NAFTA example with fixest

### ISSUE THREAD

**Issue by mmc00** [pachadotdev/tradepolicy#2]
Hi

I checked your question about: "Three or more FEs: fixest vs lfe vs base vs Stata (reghdfe) #286" in the fixest package. And I am wondering if you did something special in the of the fepois function call, because I could not replicate the glm results.

I attach my script
[04_pacha.txt](https://github.com/pachadotdev/tradepolicy/files/8364764/04_pacha.txt)
.

**Comment by pachadotdev** [comment]
> 

hi!
I'm super busy, but I added this to my google calendar, you'll get a detailed reply nex Thu in the morning

**Comment by pachadotdev** [comment]
hi
I've pushed the results now, as a comparison I checked the excel file that comes with the book, where it looks some columns have flipped names
to be sure, I checked table 2 in this article https://www.econstor.eu/bitstream/10419/144543/1/86371790X.pdf, which is the same as my replication., with the same columns as in the excel
